title: Go.Davsk.Net
logo: /assets/img/logo.png
description: Go.Davsk.Net is a list of Go packages available for import.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimalremote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
